[package]
name = "reskia-sys"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true
links = "reskia"

[lib]
path = "src/lib.rs"

[build-dependencies]

[lints]
workspace = true
